---
- name: Configure Server
  become: true
  hosts: server
  roles:
    - role: geerlingguy.docker
  tasks:
    - name: Pull docker dumbproxy image
      tags: dumbproxy_pull
      community.docker.docker_image_pull:
        name: ghcr.io/senseunit/dumbproxy
        tag: 1.11

    - name: Create and start dumbproxy container
      tags: dumbproxy_create
      community.docker.docker_container:
        name: dumbproxy
        image: ghcr.io/senseunit/dumbproxy:1.11
        entrypoint:
          - /dumbproxy
          - -bind-address
          - ":{{ dumbproxy_port }}"
          - -auth
          - 'static://?username={{ dumbproxy_user }}&password={{ dumbproxy_password }}'
        detach: true
        recreate: true
        restart_policy: unless-stopped
        security_opts:
          - no-new-privileges
        exposed_ports:
          - "{{ dumbproxy_port }}"
        published_ports:
          - "{{ dumbproxy_port }}:{{ dumbproxy_port }}"
